### ISSUE TITLE
find_organizations got an unexpected keyword

### ISSUE THREAD

**Issue by avarf** [influxdata/influxdb-client-python#246] opened 2021-05-09 21:51 UTC
Hi,
I am trying to follow the bucket management example (https://github.com/influxdata/influxdb-client-python/blob/master/examples/buckets_management.py#L20) but I am getting an error when I want to get the `org_id`.

My code:
```python
import influxdb_client
from influxdb_client.client.write_api import SYNCHRONOUS

class DB:
    """
    DB class provides required functionalities to read and write to DB
    https://github.com/influxdata/influxdb-client-python/tree/master/examples
    """

    def __init__(self, url="http://localhost:8086", token = "mytoken", org = "myorg"):
        self.url = url
        self.client = influxdb_client.InfluxDBClient(
            url=self.url,
            token=token,
            org=org
        )
        self.write_api = self.client.write_api(write_options=SYNCHRONOUS)
        self.buckets_api = self.client.buckets_api()
        self.org_id = self.client.organizations_api().find_organizations(org=org)[0]
```
Error:
```bash
Traceback (most recent call last):
  File "./db-test.py", line 3, in <module>
    db = DB()
  File "/home/workspace/db/db.py", line 19, in __init__
    self.org_id = self.client.organizations_api().find_organizations(org=org)[0]
TypeError: find_organizations() got an unexpected keyword argument 'org'
```

System info:
- OS: Ubuntu 18.04
- client:
```bash
$ pip freeze | grep influx
influxdb==4.1.1
influxdb-client==1.17.0
```

**Comment by bednar** [comment] 2021-05-10 09:02
Hi @avarf,

thanks for using our client. 

It is caused by missing supports for filtering organization by `name`. This feature will be introduced in upcoming release [1.18.0](https://github.com/influxdata/influxdb-client-python/milestone/20?closed=1).

Please use following version of example: https://github.com/influxdata/influxdb-client-python/blob/4792fd5a285817f99391b792150497814ce4b1e5/examples/buckets_management.py#L20

Regards

**Comment by bednar** [comment] 2021-06-02 07:28
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Closed by bednar** 2021-06-02 07:28 UTC
Labels: question
